#define FORMAT_TIMESLOT_DATE                @"yyyy-MM-dd'T'HH:mm:ssZZZZZ"


#define FIELD_TIMESLOT_ACTIVITY         @"activity"
#define FIELD_TIMESLOT_ID               @"timeslot_id"
#define FIELD_TIMESLOT_REFID            @"timeslot_refid"
#define FIELD_TIMESLOT_ACTIVITY_ID      @"activity_id"
#define FIELD_TIMESLOT_START            @"start"
#define FIELD_TIMESLOT_END              @"end"
#define FIELD_TIMESLOT_TIMEZONE_OFFSET  @"timezone_offset"
#define FIELD_TIMESLOT_MAX_GUEST        @"max_guests"
#define FIELD_TIMESLOT_AVAILABLE_SPOTS  @"available_spots"
#define FIELD_TIMESLOT_FAKE_ID          @"fid"
#define FIELD_TIMESLOT_MANAGER_NOTES    @"manager_notes"
#define FIELD_TIMESLOT_GUIDE_NOTES      @"guide_notes"
#define FIELD_TIMESLOT_MEETING_LOCATION @"meeting_location"
#define FIELD_TIMESLOT_TIME_SERIES_TYPE @"time_series_type"
#define FIELD_TIMESLOT_DATE             @"date"
#define FIELD_TIMESLOT_GUIDE_IDS        @"guide_ids"
#define FIELD_TIMESLOT_AVAILABILITY_STATUS  @"availability_status"